name: Content to product pipeline
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wordpress_test
          MYSQL_HOST: localhost
          MYSQL_PASSWORD: wordpress_test
          MYSQL_ROOT_PASSWORD: wordpress_test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Install composer
        run: |
          composer install
      - name: Code Formating
        run: |
          chmod +x ${{ github.workspace }}/vendor/bin/phpcbf
          ${{ github.workspace }}/vendor/bin/phpcbf
      - name: Code Sniffing
        run: |
          chmod +x ${{ github.workspace }}/vendor/bin/phpcs
          ${{ github.workspace }}/vendor/bin/phpcs
      - name: Unit Testing
        run: |
          bash ${{ github.workspace }}/bin/install-wp-tests.sh wordpress_test wordpress_test 'wordpress_test' 0.0.0.0:33306
          chmod +x ${{ github.workspace }}/vendor/bin/phpunit
          ${{ github.workspace }}/vendor/bin/phpunit
      - name: Deleting Test folder
        run: |
          export COMPOSER_PROCESS_TIMEOUT=900
          rm -rf ${{ github.workspace }}/tests
      - name:  Deleting bin folder
        run: |
          rm -rf ${{ github.workspace }}/bin
      - name:  Deleting files
        run: |
          rm -f ${{ github.workspace }}/.phpcs.xml.dist
          rm -f ${{ github.workspace }}/phpunit.xml.dist
          rm -f ${{ github.workspace }}/.composer.json
      - name:  Deleting github folder
        run: |
          rm Z-rf ${{ github.workspace }}/.github
      - run: echo "🍏 This job's status is ${{ job.status }}."
