name: Content product pipeline
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wordpress_test
          MYSQL_HOST: localhost
          MYSQL_PASSWORD: wordpress_test
          MYSQL_ROOT_PASSWORD: wordpress_test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Code Formating
        run: |
          chmod +x /home/runner/work/content-to-product/vendor/bin/phpcbf
          /home/runner/work/content-to-product/vendor/bin/phpcbf
      - name: Code Sniffing
        run: |
          chmod +x /home/runner/work/content-to-product/vendor/bin/phpcs
          /home/runner/work/content-to-product/vendor/bin/phpcs
      - name: Unit Testing
        run: |
          bash /home/runner/work/content-to-product/bin/install-wp-tests.sh wordpress_test wordpress_test 'wordpress_test' 0.0.0.0:33306
          chmod +x /home/runner/work/content-to-product/vendor/bin/phpunit
          /home/runner/work/content-to-product/vendor/bin/phpunit
      - run: echo "🍏 This job's status is ${{ job.status }}."
